#164139687 Add ratings to an article
andela/vidar-ah-backend pull request #30
Opened 2019-03-14 17:25 UTC by kleva-j

#### What does this PR do?
Adds the feature for users to be able to rate an article.
#### Description of Task to be completed?
Users should be able to rate an article.

This new endpoint takes these input:
- `rating` from the `req.body` object
- `articleId` from the `req.param` object
#### How should this be manually tested?
- run  `npm run db-migrate` to get all database migration updates.
- make a 'POST' request to the `/api/v1/articles/rate/:articleId` route.
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/164139687

#### Screenshots (if appropriate)
#### Questions:
N/A

2019-03-15 17:09 UTC, olajide1234 reviewed
Great job. Please look at these few comments.

2019-03-15 17:09 UTC, olajide1234 commented on controllers/articles.js
> +      const articleExist = await Article.findOne({ where: { id: articleId } });
Try using middleware to find if the article exists and if the user owns the article. Let's sync.

2019-03-15 17:09 UTC, olajide1234 commented on controllers/articles.js
> +            articleRating: (await Ratings.create({
Slick!

2019-03-18 12:02 UTC, codinger41 approved these changes

2019-03-18 14:07 UTC, youngestdj reviewed
Fix hound errors and you'd be good to go

2019-03-18 14:18 UTC, youngestdj approved these changes

2019-03-18 19:26 UTC, 9jaswag requested changes

2019-03-18 19:26 UTC, 9jaswag commented on middleware/checkIfArticleExist.js
> +import { Article } from '../models';
@kleva-j this file can be named something better

2019-03-18 19:42 UTC, 9jaswag commented on doc.json
> +          "Articles"
@kleva-j why all these changes here?

2019-03-20 16:46 UTC, 9jaswag approved these changes

2019-03-20 16:46 UTC, merged