#164139699 Add functionality to report articles
andela/vidar-ah-backend pull request #59
Opened 2019-04-24 13:27 UTC by leksyib

#### What does this PR do?
It adds the functionality for users to report articles
#### Description of Task to be completed?
- adds a new model for reporting articles
- adds an endpoint to report articles
- adds an endpoint to get all reports

#### How should this be manually tested?
- Make a post request as a logged in user to the `/api/v1/report/:articleSlug` endpoint with a request body that contains `type` and `message`.
- Make a get request as an admin to the `/api/v1/reports` endpoint to get all reports.
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/164139699

#### Screenshots (if appropriate)
#### Questions:
N/A

2019-04-24 13:39 UTC, olajide1234 approved these changes

2019-04-24 13:48 UTC, chingsley approved these changes

2019-04-25 09:11 UTC, 9jaswag requested changes

2019-04-25 09:11 UTC, 9jaswag commented on controllers/reports.js
> +  static async reportAnArticle(req, res) {
@leksyib `reportArticle` is a better method name.

2019-04-25 09:11 UTC, 9jaswag commented on controllers/reports.js
> +  static async getAllReports(req, res) {
@leksyib `getReports`

2019-04-25 11:08 UTC, 9jaswag requested changes

2019-04-25 11:08 UTC, 9jaswag commented on routes/v1.js
> +  '/report/:slug',
@leksyib please change this based on our latest discussion.

2019-04-25 11:57 UTC, 9jaswag approved these changes

2019-04-25 11:57 UTC, merged